import Vue from 'vue'
import Vuex from 'vuex'

Vue.use(Vuex)

const createStore = () =>
new Vuex.Store({
  state: {
    menuIsActive: false,
    intro: {
      heading: '10 Steps to Perfect Skin',
      clicked: false,
      slug: '',
      text: "K-beauty is the latest trend in the beauty world. People are beginning to realize that the secret to great skin lies in the Korean method of layering on multiple targeted products. If you'd like to get the best skin of your life but don't know where to start, experiment with these products from Nigel Beauty in Los Angeles.",
      fulltext: "K-beauty is the latest trend in the beauty world. People are beginning to realize that the secret to great skin lies in the Korean method of layering on multiple targeted products. If you'd like to get the best skin of your life but don't know where to start, experiment with these products from Nigel Beauty in Los Angeles.",
      size: true},
    regimen: [
      {id: 0},
      {heading: 'Cleansing Oil',
        id: 1,
        slug: '1-cleansing-oil',
        productname: 'Chica Y Chico Killing Star Cleanser',
        image: 'https://www.nigelbeauty.com/images/Product/medium/30770.jpg',
        url: 'https://www.nigelbeauty.com/p-30770-killing-star-cleanser-150ml.aspx',
        clicked: false,
        text: '1',
        fulltext: "The first unusual thing you'll notice about your new K-beauty skincare routine is the double cleanse. It's not as crazy as it sounds. It makes a huge difference to start your routine with an oil-based or cream-based cleanser that loosens your makeup, skin oils and dead skin cells before you go in with a more powerful cleanser. <a href='https://www.nigelbeauty.com/p-30770-killing-star-cleanser-150ml.aspx'>The Killing Star Cleanser</a> contains four different natural oils that remove impurities without stripping your skin.",
        size: false},
      {heading: 'Light Cleanser',
        id: 2,
        slug: '2-light-cleanser',
        productname: 'Back to Iceland Cleansing Water',
        image: 'https://www.nigelbeauty.com/images/Product/medium/30493.jpg',
        url: 'https://www.nigelbeauty.com/p-30493-back-to-iceland-cleansing-water-915oz.aspx',
        clicked: false,
        text: '2',
        fulltext: 'Follow up with a mild cleanser like the <a href="https://www.nigelbeauty.com/p-30493-back-to-iceland-cleansing-water-915oz.aspx">Back to Iceland Cleansing Water</a>, which will be more effective when used on skin that has already been treated to an oil cleanse. The cleansing water removes any lingering traces of the oil cleanser and final bits of dirt and makeup.',
        size: false},
      {heading: 'Exfoliate',
        id: 3,
        slug: '3-exfoliate',
        url: 'https://www.nigelbeauty.com/p-32699-organic-mineral-peel-face-2oz.aspx',
        productname: 'O.R.G. Skincare Mineral Peel Face',
        image: 'https://www.nigelbeauty.com/images/Product/medium/32699.jpg',
        clicked: false,
        text: '3',
        fulltext: 'Now that your face is clean, use a mild exfoliant to dissolve away the top layers of skin. These top layers are where the visible signs of aging are most apparent. When you safely and gently remove these dead skin cells, it triggers your skin to generate new, fresh cells. This spray-on exfoliator is a convenient physical buffing agent that is safe to use up to three times a week.',
        size: false},
      {heading: 'Peel-Off Mask',
        id: 4,
        slug: '4-peel-off-mask',
        url: 'https://www.nigelbeauty.com/p-32584-pore-clear-black-charcoal-peel-off-pack.aspx',
        productname: 'PureHeals Black Charcoal Peel Off Mask',
        image: 'https://www.nigelbeauty.com/images/Product/medium/32584.jpg',
        clicked: false,
        text: '4',
        fulltext: 'This <a href="https://www.nigelbeauty.com/p-32584-pore-clear-black-charcoal-peel-off-pack.aspx">peel-off charcoal mask</a> is another helpful non-daily skincare treatment. It draws sebum out of your skin for a refined surface texture with less visible pores. It also pulls blackheads out of problem areas like your nose, chin and forehead. Be careful not to use this on nights when you use the exfoliating spray. Charcoal masks are especially beneficial for oily skin, since they suck up excess oil.',
        size: false},
      {heading: 'Toner',
        id: 5,
        slug: '5-toner',
        productname: 'SKINRxLAB Madecera Essence Toner',
        image: 'https://www.nigelbeauty.com/images/Product/medium/32512.jpg',
        url: 'https://www.nigelbeauty.com/p-32512-re-turnrx-madecera-essence-toner-51oz.aspx',
        clicked: false,
        text: '5',
        fulltext: "A <a href='https://www.nigelbeauty.com/p-32512-re-turnrx-madecera-essence-toner-51oz.aspx'>treatment essence</a> is a great follow-up to a toner. This essence from <a href='https://www.nigelbeauty.com/m-857-skinrx.aspx'>SKINRx LAB</a> contains ceramides to deliver rich, anti-aging moisture.",
        size: false},
        {heading: 'Snail Serum',
        id: 6,
        slug: '6-snail-serum',
        productname: 'COSRX Snail 96 Mucin Power Essence',
        image: 'https://www.nigelbeauty.com/images/Product/medium/30497.jpg',
        url: 'https://www.nigelbeauty.com/p-30497-advanced-snail-96-mucin-power-essence.aspx',
        clicked: false,
        text: '6',
        fulltext: "Before the essence dries completely, apply a gel-like serum like the <a href='https://www.nigelbeauty.com/p-30497-advanced-snail-96-mucin-power-essence.aspx'>COSRX Snail 96 Mucin Power Essence</a>. This is when the treatments start to get a bit more intense, so its good to have laid down a foundation of lightweight water-based products first. The snail serum's antioxidant blend fends off skin cell damage from aging free radicals and also provides a bit of protection from UV rays.",
        size: false},
      {heading: 'Moisturize',
        id: 7,
        slug: '7-moisturize',
        url: 'https://www.nigelbeauty.com/p-32581-one-step-moisture-up-pad-70ct.aspx',
        image: 'https://www.nigelbeauty.com/images/Product/medium/32581.jpg',
        productname: 'COSRX Moisture Up Pad',
        clicked: false,
        text: '7',
        fulltext: "Though these treatments are good for the health of your skin, they might leave your face feeling a bit tight and sensitive. This is the right time to use a <a href='https://www.nigelbeauty.com/p-32581-one-step-moisture-up-pad-70ct.aspx'>COSRX Moisture Up Pad</a>. This product contains hyaluronic acid, which draws water moisture from the air into your skin to plump up and smooth out fine lines. Toners also prep the skin and open up your pores so they're ready to receive whatever products you apply next.",
        size: false},
      {heading: 'Sheet Mask',
        id: 8,
        slug: '8-sheet-masks',
        url: 'https://www.nigelbeauty.com/m-945-cliv.aspx',
        productname: 'CLIV Character Masks',
        clicked: false,
        text: '8',
        image: 'https://www.nigelbeauty.com/images/Product/medium/32596.jpg',
        fulltext: "If you feel you need extra moisture at this point, use a <a href='https://www.nigelbeauty.com/m-945-cliv.aspx'>CLIV character sheet mask</a>. Leave the sheet mask on for 10 to 15 minutes to give all of the nutrients and moisturizers time to absorb. After you remove the sheet, gently massage the remaining serum into your skin. Sheet masks are excellent treatments during cold, dry weather or after you've gotten a bit too much sun.",
        size: false},
      {heading: 'Eye Patches',
        id: 9,
        slug: '9-eye-patches',
        productname: 'PureHeal Ginseng Berry Eye Patches',
        clicked: false,
        url: 'https://www.nigelbeauty.com/p-32592-ginseng-berry-eye-lift-patch.aspx',
        image: 'https://www.nigelbeauty.com/images/Product/medium/32592.jpg',
        text: '9',
        fulltext: "We can't forget the delicate skin under your eyes. The skin in this area is especially fragile and prone to aging before the rest of your face. Place these <a href='https://www.nigelbeauty.com/p-32592-ginseng-berry-eye-lift-patch.aspx'>PureHeal's Ginseng Berry Eye Patches</a> under your eyes for a quick infusion of energizing antioxidants to keep your skin firm and healthy.",
        size: false},
      {heading: 'Cream',
        id: 10,
        slug: '10-cream',
        productname: 'Skin&Lab Red Cream',
        image: 'https://www.nigelbeauty.com/images/Product/medium/32597.jpg',
        url: 'https://www.nigelbeauty.com/p-32597-red-cream-50ml.aspx',
        clicked: false,
        text: '10',
        fulltext: "The final step in your new skincare routine is the <a href='https://www.nigelbeauty.com/p-32597-red-cream-50ml.aspx'>Skin&Lab Red Cream</a>. It is a rich moisturizer that is chock full of antioxidants and stem cells to slow down your skin's natural life cycle. Your skin will stay younger longer. Even oily skin can benefit from a thick night cream. The sebaceous glands produce less oil when you treat your face to clean, fresh moisture.",
        size: false}
    ],
    outro:
    {heading: 'Discover K-Beauty today',
      id: 12,
      clicked: false,
      fulltext: "A regimen from Nigel Beauty is the best way to preserve the youth and beauty of your skin. This site shows you where to buy the products and where to apply them for optimal results. Before you know it, you'll have the skin of someone decades younger.",
      size: true},
    animParams: {
      dur1: 0.25,
      dur2: 0.15,
      dur3: 0.35,
      ease: '',
      elastic: ''
    }
  },
  mutations: {
        SET_REGIMEN (state, regimen, {commit}) {
          state.regimen = regimen
        }
  }

})

export default createStore

